import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopNav from "@/components/TopNav";
import LeftNav from "@/components/LeftNav";
import RightNav from "@/components/RightNav";
import BottomNav from "@/components/BottomNav";
import AuthProvider from "@/components/AuthProvider";
import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";
import { Toaster } from "@/components/ui/toaster";
import { addDoc, collection, doc, setDoc } from "firebase/firestore";
import { db } from "@/firebase.config";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  if (session) {
    await addDoc(collection(db, "all-users"), {
      userName: session?.user?.name!,
      userEmail: session?.user?.email!,
      userImage: session?.user?.image!,
    });
  }
  console.log(session);
  if (!session) {
    redirect("/api/auth/signin");
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <div className="h-screen w-full flex flex-col relative overflow-hidden">
            <TopNav />
            <div className="grid grid-cols-10 w-full relative h-full z-10">
              <LeftNav />
              <div className="col-span-10 md:col-span-7 lg:col-span-6 xl:col-span-5 w-full overflow-y-scroll scrollbar-hide h-full bg-darker">
                {children}
              </div>
              <RightNav />
            </div>
            <BottomNav />
          </div>
        </AuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
